# Generated by Django 5.0.5 on 2024-05-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
