# Generated by Django 5.0.5 on 2024-05-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_usuario_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='nome',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quarto',
            name='descricao',
            field=models.TextField(max_length=230),
        ),
    ]
