# Generated by Django 5.0.5 on 2024-05-21 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_quarto_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('idade', models.IntegerField()),
                ('data', models.CharField(max_length=20)),
                ('quarto', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='nome',
        ),
    ]
